# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 05:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('jefe', models.CharField(max_length=30)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamwork.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('apellidos', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10)),
                ('descripcion', models.CharField(max_length=300)),
                ('hecho', models.BooleanField(default='false')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamwork.Equipo')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamwork.Estudiante')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='integrantes',
            field=models.ManyToManyField(to='teamwork.Estudiante'),
        ),
    ]
