# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0002_auto_20171121_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='respuesta',
            field=models.TextField(default=''),
        ),
    ]
