# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-30 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0003_tarea_respuesta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='hecho',
            field=models.IntegerField(default=0),
        ),
    ]
