# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 21:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0005_auto_20171204_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('visto', models.BooleanField()),
                ('fecha', models.DateTimeField()),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamwork.Estudiante')),
            ],
        ),
    ]
