# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-11 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0006_notificaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificaciones',
            name='responsable',
        ),
        migrations.AddField(
            model_name='notificaciones',
            name='para',
            field=models.ManyToManyField(to='teamwork.Estudiante'),
        ),
    ]
