# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0007_auto_20171211_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('visto', models.BooleanField()),
                ('fecha', models.DateTimeField()),
                ('para', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='teamwork.Estudiante')),
            ],
        ),
        migrations.RemoveField(
            model_name='notificaciones',
            name='para',
        ),
        migrations.DeleteModel(
            name='Notificaciones',
        ),
    ]
