# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0009_auto_20171212_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='avatar',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
