# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-19 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0010_estudiante_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='avatar',
            field=models.ImageField(upload_to=None),
        ),
    ]
