# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0012_auto_20171221_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='avatar',
            field=models.ImageField(upload_to='teamwork/static/img/avatars'),
        ),
    ]
