# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0013_auto_20171221_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='llave',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='avatar',
            field=models.ImageField(upload_to='teamwork/static/teamwork/img/avatars'),
        ),
    ]
