# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-21 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0014_auto_20171221_1636'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=120)),
                ('de', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamwork.Estudiante')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamwork.Equipo')),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teamwork.Tarea')),
            ],
        ),
    ]
