# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0016_remove_mensaje_equipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 14, 43, 26, 409418)),
        ),
    ]
