# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-22 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0017_mensaje_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 22, 18, 57, 37, 35527)),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='texto',
            field=models.CharField(max_length=80),
        ),
    ]
