# Generated by Django 2.0 on 2018-08-05 03:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teamwork', '0020_auto_20180504_1656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='avatar',
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 5, 5, 20, 58, 583663)),
        ),
    ]
